#!/bin/bash
IMG_DIR="/Users/fukushima/Documents/config/iterm2/picture"
IMG_FILE=`find $IMG_DIR/genshin -type f | grep -e .*.jpg$ -e .*.png$ | shuf | head -1`

/usr/bin/osascript <<EOF
tell application "iTerm2"
  tell current session of current window
    set background image to "${IMG_FILE}"
  end tell
end tell
EOF
